name: furnify
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2801.0
  flutter_svg: ^2.0.10+1
  flutter_rating: ^2.0.2
  intl: ^0.20.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  uuid: ^4.5.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.6.0
  dice_bear: ^0.1.7
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  share_plus: ^10.1.3
  http: ^1.2.2
  path_provider: ^2.1.5
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.4
  riverpod_annotation: ^2.6.1
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  url_launcher: ^6.3.1
  razorpay_flutter: ^1.3.7
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - .env
